### ISSUE TITLE
Can't install on server

### ISSUE THREAD

**Issue by bartjroos** [Radiuscollege/stage#1]
On the server i run _npm install --production_. Running _npm run build_ after that generates a lot of errors, because _build.js_ requires a lot of modules that are in the _devDependies_ of package.json. These shouldn't be installed on the server.

Possible solution: clean up build/build.js?

When running _npm install_ (without _--production_), and then running _npm run build_ this error occurs:
![error](https://user-images.githubusercontent.com/28384433/33091678-1befd9c4-cef8-11e7-9778-f6c722c5d5a5.png)

**Comment by Feddman** [comment]
use dist folder as entry point
